# Generated by Django 5.1.4 on 2024-12-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
