# Generated by Django 5.1.4 on 2025-02-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_location",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Location"
            ),
        ),
    ]
