# Generated by Django 5.1.4 on 2024-12-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_user_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_location",
            field=models.CharField(
                blank=True, default="myCity", max_length=255, null=True
            ),
        ),
    ]
